"""add reset password

Revision ID: ddb7897e1ab5
Revises: aac4bd235c1d
Create Date: 2023-10-16 00:36:12.731605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddb7897e1ab5'
down_revision: Union[str, None] = 'aac4bd235c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    op.add_column('users', sa.Column('password_needs_reset', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('admin', 'moderator', 'user', name='roles'), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_needs_reset')
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
