"""add user roles

Revision ID: ed231f88afd5
Revises: 40629eabf872
Create Date: 2023-09-27 06:41:10.097224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed231f88afd5"
down_revision: Union[str, None] = "40629eabf872"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE roles AS ENUM('admin', 'moderator', 'user')")  # MANUALLY!
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("admin", "moderator", "user", name="roles"),
            nullable=True,
            default="user",  # MANUALLY!
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    op.execute("DROP TYPE role")  # MANUALLY!
    # ### end Alembic commands ###
